server:
  port: 8081
  
mybatis:
  mapperLocations: classpath:mapping/*.xml
  
spring:
  datasource:
    name: seckill
    url: jdbc:mysql://localhost:3306/seckill2
    username: root
    password: lizhimysql
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
