server:
  port: 8081
  
mybatis:
  mapperLocations: classpath:mapping/*.xml
  
spring:
  datasource:
    name: seckill
    url: jdbc:mysql://localhost:3306/seckill2
    username: root
    password: lizhimysql
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
