package com.seckill2.model;

import java.util.Date;

public class Seckill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_id
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private Integer seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.name
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.number
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.start_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.end_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.create_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_id
     *
     * @return the value of seckill.seckill_id
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public Integer getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_id
     *
     * @param seckillId the value for seckill.seckill_id
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setSeckillId(Integer seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.name
     *
     * @return the value of seckill.name
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.name
     *
     * @param name the value for seckill.name
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.number
     *
     * @return the value of seckill.number
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.number
     *
     * @param number the value for seckill.number
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.start_time
     *
     * @return the value of seckill.start_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.start_time
     *
     * @param startTime the value for seckill.start_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.end_time
     *
     * @return the value of seckill.end_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.end_time
     *
     * @param endTime the value for seckill.end_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.create_time
     *
     * @return the value of seckill.create_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.create_time
     *
     * @param createTime the value for seckill.create_time
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}