package com.seckill2.model;

public class SuccessKilledKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.seckill_id
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private Long seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.user_phone
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    private Long userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.seckill_id
     *
     * @return the value of success_killed.seckill_id
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.seckill_id
     *
     * @param seckillId the value for success_killed.seckill_id
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.user_phone
     *
     * @return the value of success_killed.user_phone
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.user_phone
     *
     * @param userPhone the value for success_killed.user_phone
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }
}