package com.seckill2.dao;

import com.seckill2.model.SuccessKilled;
import com.seckill2.model.SuccessKilledKey;

public interface SuccessKilledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    int deleteByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    int insert(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    int insertSelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    SuccessKilled selectByPrimaryKey(SuccessKilledKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    int updateByPrimaryKeySelective(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table success_killed
     *
     * @mbg.generated Sun Jan 26 23:09:22 GMT 2020
     */
    int updateByPrimaryKey(SuccessKilled record);
}